In [1]:
import numpy as np

In [6]:
z = np.array([-2,-1,0,1])

In [7]:
np.maximum(z,0) # ReLU

array([0, 0, 0, 1])

In [3]:
!cd img && ls

01_relu.png        03_embedding.png   05_tweet.png       07_propagation.png
02_serial.png      04_mean.png        06_train.png


![image.png](img/01_relu.png)
Source: https://www.coursera.org/learn/sequence-models-in-nlp

![image.png](img/02_serial.png)
Source: https://www.coursera.org/learn/sequence-models-in-nlp/supplement/E3Yfq/serial-layer

In [9]:
def DenseL1(x:np.array):
    return x * 2

def ActiReLu(z:np.array):
    return np.maximum(z,0)

y = ActiReLu(DenseL1(x))
y

array([0, 0, 0, 2])

# Warum?
![image.png](img/05_tweet.png)
Source: https://www.coursera.org/learn/sequence-models-in-nlp

# Embedding Layer
![image.png](img/03_embedding.png)
Source: https://www.coursera.org/learn/sequence-models-in-nlp/supplement/wfa54/other-layers

Anzahl der Parameter (Weights) ~ n vocabs * n Embedding Layers?

# Mean Layer
![image-2.png](img/04_mean.png)

In [15]:
embedding_layer = np.array([[0.02, 0.006],
                          [-0.003, 0.01],
                          [0.009, 0.01]])

mean_layer = round(embedding_layer.mean(),3) * np.array([[1],[1]])

mean_layer

array([[0.009],
       [0.009]])

# Training
Die Ableitung kann sehr einfach gebildet werden. Ich wünschte, ich hätte so ein Werkzeug damals im Matheleistungskurs gehabt ;).

![image.png](img/06_train.png)
Source: https://www.coursera.org/learn/sequence-models-in-nlp/supplement/JAcvF/training

In [4]:
import trax

In [9]:
def f(x):
    return 3*x**2 + x

grad_f = trax.fastmath.grad(f)

Nicht ganz so straight forward ist die Anwendung der Ableitung. Auf der Grafik sieht es einfach aus. Allerdings führte meine naive (vanilla python) Ausführung des Codes zu Tracebacks.

![image.png](img/07_propagation.png)
Source: https://www.coursera.org/learn/sequence-models-in-nlp/supplement/JAcvF/training

In [20]:
x = np.array([1,2])
# trax.fastmath.grad(f)(x)